=== maksym-antoniuk/epam-cource-Practice7/input.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--  XML schema -->

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://nure.ua/antoniuk/SummaryTask3/entity"
	xmlns:tns="http://nure.ua/antoniuk/SummaryTask3/entity">

	<xsd:element name="Fond">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="gem"
							 type="tns:Gem" maxOccurs="unbounded" minOccurs="0"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>


	<xsd:complexType name="Gem">
		<xsd:sequence>
			<xsd:element name="name" type="tns:Name"/>
			<xsd:element name="preciousness" type="tns:Preciousness"/>
			<xsd:element name="origin" type="tns:Origin"/>
			<xsd:element name="parameters" type="tns:VisualParam"/>
			<xsd:element name="value" type="tns:Value"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="VisualParam">
		<xsd:all>
			<xsd:element name="color" type="tns:Color" minOccurs="0" maxOccurs="1"/>
			<xsd:element name="transparency" type="tns:RestrictedPercentage" minOccurs="0" maxOccurs="1"/>
			<xsd:element name="cut" type="tns:Cut" minOccurs="0" maxOccurs="1"/>
		</xsd:all>
	</xsd:complexType>

	<xsd:simpleType name="RestrictedPercentage">
		<xsd:restriction base="xsd:double">
			<xsd:minInclusive value="0"/>
			<xsd:maxInclusive value="1"/>
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="Cut">
		<xsd:restriction base="xsd:int">
			<xsd:minInclusive value="4"/>
			<xsd:maxInclusive value="15"/>
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="Value">
		<xsd:restriction base="xsd:decimal">
			<xsd:minInclusive value="0"/>
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="Color" final="restriction" >
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="green" />
			<xsd:enumeration value="red" />
			<xsd:enumeration value="blue" />
			<xsd:enumeration value="violet" />
			<xsd:enumeration value="white" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="Preciousness" final="restriction">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="драгоценный" />
			<xsd:enumeration value="полудрагоценный" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="Name">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="[A-Z][a-z]+"/>
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="Origin">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="[A-Z].+"/>
		</xsd:restriction>
	</xsd:simpleType>
</xsd:schema>

=== maksym-antoniuk/epam-cource-Practice7/input.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--  Input XML document. This XML is valid against Test.xsd XML schema-->

<st3:Fond xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		  xmlns:st3="http://nure.ua/antoniuk/SummaryTask3/entity"
		  xsi:schemaLocation="http://nure.ua/antoniuk/SummaryTask3/entity input.xsd">

	<gem>
		<name>Rubin</name>
		<preciousness>драгоценный</preciousness>
		<origin>Ukraine, Kharkiv</origin>
		<parameters>
			<color>red</color>
            <cut>4</cut>
            <transparency>0.1</transparency>
		</parameters>
        <value>0.3333</value>
	</gem>

    <gem>
		<name>Ametist</name>
		<preciousness>драгоценный</preciousness>
		<origin>USA, Kharkiv</origin>
		<parameters>
			<color>violet</color>
            <transparency>0.7</transparency>
		</parameters>
        <value>0.86</value>
	</gem>

    <gem>
		<name>Izumrud</name>
		<preciousness>драгоценный</preciousness>
		<origin>Ukraine, Lviv</origin>
		<parameters>
			<color>green</color>
            <cut>11</cut>
		</parameters>
        <value>1.4</value>
	</gem>

    <gem>
		<name>Saphir</name>
		<preciousness>полудрагоценный</preciousness>
		<origin>Germany, Frankfurt</origin>
		<parameters>
			<color>violet</color>
            <cut>7</cut>
            <transparency>0.9</transparency>
		</parameters>
        <value>0.788</value>
	</gem>
</st3:Fond>
